name: CUMAb
channels:
  - bioconda
  - conda-forge
  - schrodinger
  - defaults
dependencies:
  - python
  - biopython
  - pandas
  - pymol-open-source
  - pip
  - hmmer
  - pip:
    - antpack # requires sudo
